### ISSUE TITLE
vue-particles doesn't work with nuxt.js

### ISSUE THREAD

**Issue by Leooman** [Leooman/Nadmin#1]
```
Nuxt.js Error:

/Users/roslanelyashiv/Desktop/VUEJS/nuxt-starter/node_modules/vue-particles/src/vue-particles/index.js:2
import particles from './vue-particles.vue'
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at r (/Users/roslanelyashiv/Desktop/VUEJS/nuxt-starter/node_modules/vue-server-renderer/build.js:6964:16)
    at Object.<anonymous> (webpack:/external "vue-particles":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 7eaa50f5c611e7151c2d:25:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:2231:72)
    at __webpack_require__ (webpack:/webpack/bootstrap 7eaa50f5c611e7151c2d:25:0)
    at Object.module.exports.module.exports.list (.nuxt/index.js:88:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 7eaa50f5c611e7151c2d:25:0)
    at Object.<anonymous> (server-bundle.js:1908:65)
```

**Comment by Leooman** [comment]
The best way I have found to implement vue-particles with Nuxt JS is to disable server side rendering after implementing it as a plugin.

As mentioned in the [client-side rendering only](https://nuxtjs.org/guide/plugins#client-side-only).

> plugins/vue-particles.js 

```
import Vue from 'vue'
import VueParticles from 'vue-particles'

export default () => {
	Vue.use(VueParticles)
}
```

> nuxt.config.js 

```
plugins: [
    {src:"~plugins/vue-particles",ssr:false}
]
```

> vue-particles tag

but when you use vue-particles tag like this:

```
<vue-particles color="#fff"/>
```

you may get another error:

```
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

you could try wrapping the component with `<no-ssr/>`, or moving all dom manipulations to the `mounted`lifecycle hook. 

```
<no-ssr>
	<vue-particles color="#fff"/>
</no-ssr>
```
